from .userSerializer import UserSerializer
from .personalSaludSerializer import PersonalSaludSerializer
from .auxiliarSerializer import AuxiliarSerializer
from .pacienteSerializer import PacienteSerializer
from .familiarSerializer import FamiliarSerializer
from .historiaClinicaSerializer import HistoriaClinicaSerializer
from .signosVitalesSerializer import SignosVitalesSerializer
from .sugerenciasSerializer import SugerenciasSerializer